# Generated by Django 2.0 on 2017-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171221_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
    ]
