# Generated by Django 2.0 on 2017-12-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171221_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alt_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
